name: EAS Android APK

on:
  workflow_dispatch:

env:
  EXPO_PROJECT_ID: 70f0734d-28df-4fa3-9351-688a40abc45d

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Install EAS CLI
        run: npm i -g eas-cli

      # >>> Etapa nova: configura o projeto no EAS (idempotente)
      - name: Init EAS project (first run)
        run: eas init --id "$EXPO_PROJECT_ID" --non-interactive || true
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download APK
        if: always()
        run: echo "Done"
