name: Build Android (EAS)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          # sem cache para não exigir lockfile

      - name: Instalar EAS CLI
        run: npm install -g eas-cli

      - name: Instalar dependências
        run: npm install

      - name: Build APK (produção)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production --non-interactive
```0
