name: Build Android APK (EAS)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Build APK (cloud)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --profile production --non-interactive --wait

      - name: Download APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build:download --platform android --profile production --latest --path app.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app.apk
```0
