name: Build Android (EAS)

on:
  push:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar EAS CLI
        run: npm i -g eas-cli

      - name: Login no EAS
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build APK (produção)
        run: eas build --platform android --profile production --non-interactive
```0
